# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Publish Package

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          working-directory: packages/socketio-decorator
      - run: npm ci
      - run: npm run build
      - run: cp ../../README.md dist/README.md
      - run: cp ../../LICENCE dist/LICENCE
      - run: cp package.json dist/package.json
      - run: ls

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: npm publish packages/socketio-decorator/dist
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}