name: Test Pipeline

on:
  pull_request:
    branches:
      - master
      - develop

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20

    - name: Install dependencies
      run: npm i
      working-directory: packages/socketio-decorator

    - name: Run unit tests
      run: npm run test
      working-directory: packages/socketio-decorator
      continue-on-error: false
